INSERT INTO Genres (genre_id, genre_name) VALUES (1, 'hip hop');
INSERT INTO Genres (genre_id, genre_name) VALUES (2, 'blue-eyed soul');
INSERT INTO Genres (genre_id, genre_name) VALUES (3, 'salsa');
INSERT INTO Genres (genre_id, genre_name) VALUES (4, 'pop rock');
INSERT INTO Genres (genre_id, genre_name) VALUES (5, 'pop punk');
INSERT INTO Genres (genre_id, genre_name) VALUES (6, 'southern gospel');
INSERT INTO Genres (genre_id, genre_name) VALUES (7, 'breakbeat');
INSERT INTO Genres (genre_id, genre_name) VALUES (8, 'post-hardcore');
INSERT INTO Genres (genre_id, genre_name) VALUES (9, 'new wave');
INSERT INTO Genres (genre_id, genre_name) VALUES (10, 'breakcore');
INSERT INTO Genres (genre_id, genre_name) VALUES (11, 'alternative rock');
INSERT INTO Genres (genre_id, genre_name) VALUES (12, 'ccm');
INSERT INTO Genres (genre_id, genre_name) VALUES (13, 'bachata');
INSERT INTO Genres (genre_id, genre_name) VALUES (14, 'chanson');
INSERT INTO Genres (genre_id, genre_name) VALUES (15, 'quiet storm');
INSERT INTO Genres (genre_id, genre_name) VALUES (16, 'country rock');
INSERT INTO Genres (genre_id, genre_name) VALUES (17, 'chill-out');
INSERT INTO Genres (genre_id, genre_name) VALUES (18, 'qawwali');
INSERT INTO Genres (genre_id, genre_name) VALUES (19, 'hard rock');
INSERT INTO Genres (genre_id, genre_name) VALUES (20, 'indietronica');
INSERT INTO Genres (genre_id, genre_name) VALUES (21, 'classic country');
INSERT INTO Genres (genre_id, genre_name) VALUES (22, 'electric blues');
INSERT INTO Genres (genre_id, genre_name) VALUES (23, 'uk garage');
INSERT INTO Genres (genre_id, genre_name) VALUES (24, 'math-core');
INSERT INTO Genres (genre_id, genre_name) VALUES (25, 'post-grunge');
INSERT INTO Genres (genre_id, genre_name) VALUES (26, 'filk');
INSERT INTO Genres (genre_id, genre_name) VALUES (27, 'latin jazz');
INSERT INTO Genres (genre_id, genre_name) VALUES (28, 'jump blues');
INSERT INTO Genres (genre_id, genre_name) VALUES (29, 'soul jazz');
INSERT INTO Genres (genre_id, genre_name) VALUES (30, 'disco');
INSERT INTO Genres (genre_id, genre_name) VALUES (31, 'doo-wop');
INSERT INTO Genres (genre_id, genre_name) VALUES (32, 'rap');
INSERT INTO Genres (genre_id, genre_name) VALUES (33, 'charanga');
INSERT INTO Genres (genre_id, genre_name) VALUES (34, 'noise rock');
INSERT INTO Genres (genre_id, genre_name) VALUES (35, 'dance pop');
INSERT INTO Genres (genre_id, genre_name) VALUES (36, 'orchestra');
INSERT INTO Genres (genre_id, genre_name) VALUES (37, 'cool jazz');
INSERT INTO Genres (genre_id, genre_name) VALUES (38, 'gothic metal');
INSERT INTO Genres (genre_id, genre_name) VALUES (39, 'ska punk');
INSERT INTO Genres (genre_id, genre_name) VALUES (40, 'blues');
INSERT INTO Genres (genre_id, genre_name) VALUES (41, 'modern rock');
INSERT INTO Genres (genre_id, genre_name) VALUES (42, 'delta blues');
INSERT INTO Genres (genre_id, genre_name) VALUES (43, 'texas blues');
INSERT INTO Genres (genre_id, genre_name) VALUES (44, 'trip hop');
INSERT INTO Genres (genre_id, genre_name) VALUES (45, 'hardcore techno');
INSERT INTO Genres (genre_id, genre_name) VALUES (46, 'glam rock');
INSERT INTO Genres (genre_id, genre_name) VALUES (47, 'brazilian jazz');
INSERT INTO Genres (genre_id, genre_name) VALUES (48, 'gangster rap');
INSERT INTO Genres (genre_id, genre_name) VALUES (49, 'rock');
INSERT INTO Genres (genre_id, genre_name) VALUES (50, 'soft rock');
INSERT INTO Genres (genre_id, genre_name) VALUES (51, 'easy listening');
INSERT INTO Genres (genre_id, genre_name) VALUES (52, 'dance rock');
INSERT INTO Genres (genre_id, genre_name) VALUES (53, 'singer-songwriter');
INSERT INTO Genres (genre_id, genre_name) VALUES (54, 'experimental rock');
INSERT INTO Genres (genre_id, genre_name) VALUES (55, 'meditation');
INSERT INTO Genres (genre_id, genre_name) VALUES (56, 'speedcore');
INSERT INTO Genres (genre_id, genre_name) VALUES (57, 'southern rock');
INSERT INTO Genres (genre_id, genre_name) VALUES (58, 'zouk');
INSERT INTO Genres (genre_id, genre_name) VALUES (59, 'trance');
INSERT INTO Genres (genre_id, genre_name) VALUES (60, 'punk');
INSERT INTO Genres (genre_id, genre_name) VALUES (61, 'suomi rock');
INSERT INTO Genres (genre_id, genre_name) VALUES (62, 'gabba');
INSERT INTO Genres (genre_id, genre_name) VALUES (63, 'pop rap');
INSERT INTO Genres (genre_id, genre_name) VALUES (64, 'heavy metal');
INSERT INTO Genres (genre_id, genre_name) VALUES (65, 'industrial metal');
INSERT INTO Genres (genre_id, genre_name) VALUES (66, 'freestyle');
INSERT INTO Genres (genre_id, genre_name) VALUES (67, 'brill building pop');
INSERT INTO Genres (genre_id, genre_name) VALUES (68, 'melodic hardcore');
INSERT INTO Genres (genre_id, genre_name) VALUES (69, 'british pop');
INSERT INTO Genres (genre_id, genre_name) VALUES (70, 'folk-pop');
INSERT INTO Genres (genre_id, genre_name) VALUES (71, 'stoner metal');
INSERT INTO Genres (genre_id, genre_name) VALUES (72, 'western swing');
INSERT INTO Genres (genre_id, genre_name) VALUES (73, 'indie rock');
INSERT INTO Genres (genre_id, genre_name) VALUES (74, 'rap rock');
INSERT INTO Genres (genre_id, genre_name) VALUES (75, 'ranchera');
INSERT INTO Genres (genre_id, genre_name) VALUES (76, 'german pop');
INSERT INTO Genres (genre_id, genre_name) VALUES (77, 'hard bop');
INSERT INTO Genres (genre_id, genre_name) VALUES (78, 'free jazz');
INSERT INTO Genres (genre_id, genre_name) VALUES (79, 'shoegaze');
INSERT INTO Genres (genre_id, genre_name) VALUES (80, 'gospel');
INSERT INTO Genres (genre_id, genre_name) VALUES (81, 'blues-rock');
INSERT INTO Genres (genre_id, genre_name) VALUES (82, 'tech house');
INSERT INTO Genres (genre_id, genre_name) VALUES (83, 'country');
INSERT INTO Genres (genre_id, genre_name) VALUES (84, 'roots reggae');
INSERT INTO Genres (genre_id, genre_name) VALUES (85, 'freakbeat');
INSERT INTO Genres (genre_id, genre_name) VALUES (86, 'chicago soul');
INSERT INTO Genres (genre_id, genre_name) VALUES (87, 'jazz fusion');
INSERT INTO Genres (genre_id, genre_name) VALUES (88, 'new jack swing');
INSERT INTO Genres (genre_id, genre_name) VALUES (89, 'piedmont blues');
INSERT INTO Genres (genre_id, genre_name) VALUES (90, 'jazz funk');
INSERT INTO Genres (genre_id, genre_name) VALUES (91, 'male vocalist');
INSERT INTO Genres (genre_id, genre_name) VALUES (92, 'ghetto tech');
INSERT INTO Genres (genre_id, genre_name) VALUES (93, 'guitar');
INSERT INTO Genres (genre_id, genre_name) VALUES (94, 'progressive house');
INSERT INTO Genres (genre_id, genre_name) VALUES (95, 'vocal house');
INSERT INTO Genres (genre_id, genre_name) VALUES (96, 'los angeles');
INSERT INTO Genres (genre_id, genre_name) VALUES (97, 'lovers rock');
INSERT INTO Genres (genre_id, genre_name) VALUES (98, 'arabesque');
INSERT INTO Genres (genre_id, genre_name) VALUES (99, 'grunge');
INSERT INTO Genres (genre_id, genre_name) VALUES (100, 'bossa nova');
INSERT INTO Genres (genre_id, genre_name) VALUES (101, 'thrash core');
INSERT INTO Genres (genre_id, genre_name) VALUES (102, 'frevo');
INSERT INTO Genres (genre_id, genre_name) VALUES (103, 'black metal');
INSERT INTO Genres (genre_id, genre_name) VALUES (104, 'serialism');
INSERT INTO Genres (genre_id, genre_name) VALUES (105, 'bluegrass');
INSERT INTO Genres (genre_id, genre_name) VALUES (106, 'vocal jazz');
INSERT INTO Genres (genre_id, genre_name) VALUES (107, 'alternative metal');
INSERT INTO Genres (genre_id, genre_name) VALUES (108, 'flamenco');
INSERT INTO Genres (genre_id, genre_name) VALUES (109, 'honky tonk');
INSERT INTO Genres (genre_id, genre_name) VALUES (110, 'electronica');
INSERT INTO Genres (genre_id, genre_name) VALUES (111, 'country gospel');
INSERT INTO Genres (genre_id, genre_name) VALUES (112, 'hardcore punk');
INSERT INTO Genres (genre_id, genre_name) VALUES (113, 'tejano');
INSERT INTO Genres (genre_id, genre_name) VALUES (114, 'sympho black metal');
INSERT INTO Genres (genre_id, genre_name) VALUES (115, 'chamber jazz');
INSERT INTO Genres (genre_id, genre_name) VALUES (116, 'dancehall');
INSERT INTO Genres (genre_id, genre_name) VALUES (117, 'hard house');
INSERT INTO Genres (genre_id, genre_name) VALUES (118, 'gaita');
INSERT INTO Genres (genre_id, genre_name) VALUES (119, 'grime');
INSERT INTO Genres (genre_id, genre_name) VALUES (120, 'new romantic');
INSERT INTO Genres (genre_id, genre_name) VALUES (121, 'happy hardcore');
INSERT INTO Genres (genre_id, genre_name) VALUES (122, 'brazil');
INSERT INTO Genres (genre_id, genre_name) VALUES (123, 'future jazz');
INSERT INTO Genres (genre_id, genre_name) VALUES (124, 'french pop');
INSERT INTO Genres (genre_id, genre_name) VALUES (125, 'greek');
INSERT INTO Genres (genre_id, genre_name) VALUES (126, 'r&b');
INSERT INTO Genres (genre_id, genre_name) VALUES (127, 'opera');
INSERT INTO Genres (genre_id, genre_name) VALUES (128, 'ska');
INSERT INTO Genres (genre_id, genre_name) VALUES (129, 'british invasion');
INSERT INTO Genres (genre_id, genre_name) VALUES (130, 'turnablism');
INSERT INTO Genres (genre_id, genre_name) VALUES (131, 'pop folk');
INSERT INTO Genres (genre_id, genre_name) VALUES (132, 'alternative hip hop');
INSERT INTO Genres (genre_id, genre_name) VALUES (133, 'chicago blues');
INSERT INTO Genres (genre_id, genre_name) VALUES (134, 'doom metal');
INSERT INTO Genres (genre_id, genre_name) VALUES (135, 'world beat');
INSERT INTO Genres (genre_id, genre_name) VALUES (136, 'twee pop');
INSERT INTO Genres (genre_id, genre_name) VALUES (137, 'teen pop');
INSERT INTO Genres (genre_id, genre_name) VALUES (138, 'smooth jazz');
INSERT INTO Genres (genre_id, genre_name) VALUES (139, 'power pop');
INSERT INTO Genres (genre_id, genre_name) VALUES (140, 'latin pop');
INSERT INTO Genres (genre_id, genre_name) VALUES (141, 'techno');
INSERT INTO Genres (genre_id, genre_name) VALUES (142, 'viking metal');
INSERT INTO Genres (genre_id, genre_name) VALUES (143, 'rap metal');
INSERT INTO Genres (genre_id, genre_name) VALUES (144, 'requiem');
INSERT INTO Genres (genre_id, genre_name) VALUES (145, 'europop');
INSERT INTO Genres (genre_id, genre_name) VALUES (146, 'irish folk');
INSERT INTO Genres (genre_id, genre_name) VALUES (147, 'country blues');
INSERT INTO Genres (genre_id, genre_name) VALUES (148, 'instrumental pop');
INSERT INTO Genres (genre_id, genre_name) VALUES (149, 'funk metal');
INSERT INTO Genres (genre_id, genre_name) VALUES (150, 'soundtrack');
INSERT INTO Genres (genre_id, genre_name) VALUES (151, 'big beat');
INSERT INTO Genres (genre_id, genre_name) VALUES (152, 'dance-punk');
INSERT INTO Genres (genre_id, genre_name) VALUES (153, 'grindcore');
INSERT INTO Genres (genre_id, genre_name) VALUES (154, 'rockabilly');
INSERT INTO Genres (genre_id, genre_name) VALUES (155, 'broken beat');
INSERT INTO Genres (genre_id, genre_name) VALUES (156, 'miami bass');
INSERT INTO Genres (genre_id, genre_name) VALUES (157, 'vocal');
INSERT INTO Genres (genre_id, genre_name) VALUES (158, 'funky house');
INSERT INTO Genres (genre_id, genre_name) VALUES (159, 'ballet');
INSERT INTO Genres (genre_id, genre_name) VALUES (160, 'brazilian pop music');
INSERT INTO Genres (genre_id, genre_name) VALUES (161, 'j pop');
INSERT INTO Genres (genre_id, genre_name) VALUES (162, 'jazz');
INSERT INTO Genres (genre_id, genre_name) VALUES (163, 'bel canto');
INSERT INTO Genres (genre_id, genre_name) VALUES (164, 'early music');
INSERT INTO Genres (genre_id, genre_name) VALUES (165, 'musette');
INSERT INTO Genres (genre_id, genre_name) VALUES (166, 'downtempo');
INSERT INTO Genres (genre_id, genre_name) VALUES (167, 'argentine rock');
INSERT INTO Genres (genre_id, genre_name) VALUES (168, 'cantonese pop');
INSERT INTO Genres (genre_id, genre_name) VALUES (169, 'cabaret');
INSERT INTO Genres (genre_id, genre_name) VALUES (170, 'screamo');
INSERT INTO Genres (genre_id, genre_name) VALUES (171, 'bhangra');
INSERT INTO Genres (genre_id, genre_name) VALUES (172, 'heartland rock');
INSERT INTO Genres (genre_id, genre_name) VALUES (173, 'symphonic rock');
INSERT INTO Genres (genre_id, genre_name) VALUES (174, 'club');
INSERT INTO Genres (genre_id, genre_name) VALUES (175, 'instrumental rock');
INSERT INTO Genres (genre_id, genre_name) VALUES (176, 'ballad');
INSERT INTO Genres (genre_id, genre_name) VALUES (177, 'nu metal');
INSERT INTO Genres (genre_id, genre_name) VALUES (178, 'vaudeville');
INSERT INTO Genres (genre_id, genre_name) VALUES (179, 'dark ambient');
INSERT INTO Genres (genre_id, genre_name) VALUES (180, 'cumbia');
INSERT INTO Genres (genre_id, genre_name) VALUES (181, 'tango');
INSERT INTO Genres (genre_id, genre_name) VALUES (182, 'technical death metal');
INSERT INTO Genres (genre_id, genre_name) VALUES (183, 'digital hardcore');
INSERT INTO Genres (genre_id, genre_name) VALUES (184, 'celtic punk');
INSERT INTO Genres (genre_id, genre_name) VALUES (185, 'power electronics');
INSERT INTO Genres (genre_id, genre_name) VALUES (186, 'slack key guitar');
INSERT INTO Genres (genre_id, genre_name) VALUES (187, 'folk rock');
INSERT INTO Genres (genre_id, genre_name) VALUES (188, 'free music');
INSERT INTO Genres (genre_id, genre_name) VALUES (189, 'space age pop');
INSERT INTO Genres (genre_id, genre_name) VALUES (190, 'neo soul');
INSERT INTO Genres (genre_id, genre_name) VALUES (191, 'hip house');
INSERT INTO Genres (genre_id, genre_name) VALUES (192, 'lullaby');
INSERT INTO Genres (genre_id, genre_name) VALUES (193, 'chinese music');
INSERT INTO Genres (genre_id, genre_name) VALUES (194, 'california');
INSERT INTO Genres (genre_id, genre_name) VALUES (195, 'rock steady');
INSERT INTO Genres (genre_id, genre_name) VALUES (196, 'power metal');
INSERT INTO Genres (genre_id, genre_name) VALUES (197, 'humppa');
INSERT INTO Genres (genre_id, genre_name) VALUES (198, 'death metal');
INSERT INTO Genres (genre_id, genre_name) VALUES (199, 'zouklove');
INSERT INTO Genres (genre_id, genre_name) VALUES (200, 'dubstep');
INSERT INTO Genres (genre_id, genre_name) VALUES (201, 'funk');
INSERT INTO Genres (genre_id, genre_name) VALUES (202, 'classic rock');
INSERT INTO Genres (genre_id, genre_name) VALUES (203, 'surf music');
INSERT INTO Genres (genre_id, genre_name) VALUES (204, 'alternative dance');
INSERT INTO Genres (genre_id, genre_name) VALUES (205, 'world music');
INSERT INTO Genres (genre_id, genre_name) VALUES (206, 'crunk');
INSERT INTO Genres (genre_id, genre_name) VALUES (207, 'new age');
INSERT INTO Genres (genre_id, genre_name) VALUES (208, 'mariachi');
INSERT INTO Genres (genre_id, genre_name) VALUES (209, 'synthpop');
INSERT INTO Genres (genre_id, genre_name) VALUES (210, 'soul blues');
INSERT INTO Genres (genre_id, genre_name) VALUES (211, 'pop');
INSERT INTO Genres (genre_id, genre_name) VALUES (212, 'polka');
INSERT INTO Genres (genre_id, genre_name) VALUES (213, 'glitch');
INSERT INTO Genres (genre_id, genre_name) VALUES (214, 'new orleans blues');
INSERT INTO Genres (genre_id, genre_name) VALUES (215, 'world');
INSERT INTO Genres (genre_id, genre_name) VALUES (216, 'hard trance');
INSERT INTO Genres (genre_id, genre_name) VALUES (217, 'blackened death metal');
INSERT INTO Genres (genre_id, genre_name) VALUES (218, 'industrial rock');
INSERT INTO Genres (genre_id, genre_name) VALUES (219, 'visual kei');
INSERT INTO Genres (genre_id, genre_name) VALUES (220, 'kraut rock');
INSERT INTO Genres (genre_id, genre_name) VALUES (221, 'dark wave');
INSERT INTO Genres (genre_id, genre_name) VALUES (222, 'piano blues');
INSERT INTO Genres (genre_id, genre_name) VALUES (223, 'rumba');
INSERT INTO Genres (genre_id, genre_name) VALUES (224, 'dirty south rap');
INSERT INTO Genres (genre_id, genre_name) VALUES (225, 'death core');
INSERT INTO Genres (genre_id, genre_name) VALUES (226, 'reggaeton');
INSERT INTO Genres (genre_id, genre_name) VALUES (227, 'sludge metal');
INSERT INTO Genres (genre_id, genre_name) VALUES (228, 'progressive trance');
INSERT INTO Genres (genre_id, genre_name) VALUES (229, 'zydeco');
INSERT INTO Genres (genre_id, genre_name) VALUES (230, 'speed metal');
INSERT INTO Genres (genre_id, genre_name) VALUES (231, 'chicago house');
INSERT INTO Genres (genre_id, genre_name) VALUES (232, 'neue deutsche welle');
INSERT INTO Genres (genre_id, genre_name) VALUES (233, 'bass music');
INSERT INTO Genres (genre_id, genre_name) VALUES (234, 'oi');
INSERT INTO Genres (genre_id, genre_name) VALUES (235, 'underground rap');
INSERT INTO Genres (genre_id, genre_name) VALUES (236, 'louisiana blues');
INSERT INTO Genres (genre_id, genre_name) VALUES (237, 'glam metal');
INSERT INTO Genres (genre_id, genre_name) VALUES (238, 'art rock');
INSERT INTO Genres (genre_id, genre_name) VALUES (239, 'new beat');
INSERT INTO Genres (genre_id, genre_name) VALUES (240, 'stoner rock');
INSERT INTO Genres (genre_id, genre_name) VALUES (241, 'island music');
INSERT INTO Genres (genre_id, genre_name) VALUES (242, 'avantgarde metal');
INSERT INTO Genres (genre_id, genre_name) VALUES (243, 'jazz blues');
INSERT INTO Genres (genre_id, genre_name) VALUES (244, 'oldies');
INSERT INTO Genres (genre_id, genre_name) VALUES (245, 'folk metal');
INSERT INTO Genres (genre_id, genre_name) VALUES (246, 'gypsy jazz');
INSERT INTO Genres (genre_id, genre_name) VALUES (247, 'shock rock');
INSERT INTO Genres (genre_id, genre_name) VALUES (248, 'parody');
INSERT INTO Genres (genre_id, genre_name) VALUES (249, 'urban folk');
INSERT INTO Genres (genre_id, genre_name) VALUES (250, 'classic female blues');
INSERT INTO Genres (genre_id, genre_name) VALUES (251, 'electro');
INSERT INTO Genres (genre_id, genre_name) VALUES (252, 'ragtime');
INSERT INTO Genres (genre_id, genre_name) VALUES (253, 'folk');
INSERT INTO Genres (genre_id, genre_name) VALUES (254, 'motown');
INSERT INTO Genres (genre_id, genre_name) VALUES (255, 'jug band');
INSERT INTO Genres (genre_id, genre_name) VALUES (256, 'electronic');
INSERT INTO Genres (genre_id, genre_name) VALUES (257, '8-bit');
INSERT INTO Genres (genre_id, genre_name) VALUES (258, 'northern soul');
INSERT INTO Genres (genre_id, genre_name) VALUES (259, 'dub');
INSERT INTO Genres (genre_id, genre_name) VALUES (260, 'religious music');
INSERT INTO Genres (genre_id, genre_name) VALUES (261, 'afrobeat');
INSERT INTO Genres (genre_id, genre_name) VALUES (262, 'free improvisation');
INSERT INTO Genres (genre_id, genre_name) VALUES (263, 'stand-up comedy');
INSERT INTO Genres (genre_id, genre_name) VALUES (264, 'samba');
INSERT INTO Genres (genre_id, genre_name) VALUES (265, 'dream pop');
INSERT INTO Genres (genre_id, genre_name) VALUES (266, 'brutal death metal');
INSERT INTO Genres (genre_id, genre_name) VALUES (267, 'irish');
INSERT INTO Genres (genre_id, genre_name) VALUES (268, 'soukous');
INSERT INTO Genres (genre_id, genre_name) VALUES (269, 'symphony');
INSERT INTO Genres (genre_id, genre_name) VALUES (270, 'jungle music');
INSERT INTO Genres (genre_id, genre_name) VALUES (271, 'groove metal');
INSERT INTO Genres (genre_id, genre_name) VALUES (272, 'christian rock');
INSERT INTO Genres (genre_id, genre_name) VALUES (273, 'exotica');
INSERT INTO Genres (genre_id, genre_name) VALUES (274, 'goregrind');
INSERT INTO Genres (genre_id, genre_name) VALUES (275, 'modern laika');
INSERT INTO Genres (genre_id, genre_name) VALUES (276, 'jazz rap');
INSERT INTO Genres (genre_id, genre_name) VALUES (277, 'bubblegum pop');
INSERT INTO Genres (genre_id, genre_name) VALUES (278, 'reggae');
INSERT INTO Genres (genre_id, genre_name) VALUES (279, 'roots rock');
INSERT INTO Genres (genre_id, genre_name) VALUES (280, 'garage rock');
INSERT INTO Genres (genre_id, genre_name) VALUES (281, 'progressive rock');
INSERT INTO Genres (genre_id, genre_name) VALUES (282, 'swamp rock');
INSERT INTO Genres (genre_id, genre_name) VALUES (283, 'chamber pop');
INSERT INTO Genres (genre_id, genre_name) VALUES (284, 'jangle pop');
INSERT INTO Genres (genre_id, genre_name) VALUES (285, 'video game music');
INSERT INTO Genres (genre_id, genre_name) VALUES (286, 'eurodance');
INSERT INTO Genres (genre_id, genre_name) VALUES (287, 'urban');
INSERT INTO Genres (genre_id, genre_name) VALUES (288, 'congo');
INSERT INTO Genres (genre_id, genre_name) VALUES (289, 'harmonica blues');
INSERT INTO Genres (genre_id, genre_name) VALUES (290, 'alternative country');
INSERT INTO Genres (genre_id, genre_name) VALUES (291, 'comedy');
INSERT INTO Genres (genre_id, genre_name) VALUES (292, 'gothic rock');
INSERT INTO Genres (genre_id, genre_name) VALUES (293, 'hip pop');
INSERT INTO Genres (genre_id, genre_name) VALUES (294, 'christian metal');
INSERT INTO Genres (genre_id, genre_name) VALUES (295, 'celtic');
INSERT INTO Genres (genre_id, genre_name) VALUES (296, 'all-female');
INSERT INTO Genres (genre_id, genre_name) VALUES (297, 'protopunk');
INSERT INTO Genres (genre_id, genre_name) VALUES (298, 'rock ''n roll');
INSERT INTO Genres (genre_id, genre_name) VALUES (299, 'celtic rock');
INSERT INTO Genres (genre_id, genre_name) VALUES (300, 'rapcore');
INSERT INTO Genres (genre_id, genre_name) VALUES (301, 'horror punk');
INSERT INTO Genres (genre_id, genre_name) VALUES (302, 'neo-progressive');
INSERT INTO Genres (genre_id, genre_name) VALUES (303, 'patriotic');
INSERT INTO Genres (genre_id, genre_name) VALUES (304, 'comedy rock');
INSERT INTO Genres (genre_id, genre_name) VALUES (305, 'piano rock');
INSERT INTO Genres (genre_id, genre_name) VALUES (306, 'ethnic');
INSERT INTO Genres (genre_id, genre_name) VALUES (307, 'deep house');
INSERT INTO Genres (genre_id, genre_name) VALUES (308, 'melbourne');
INSERT INTO Genres (genre_id, genre_name) VALUES (309, 'industrial dance');
INSERT INTO Genres (genre_id, genre_name) VALUES (310, 'experimental pop');
INSERT INTO Genres (genre_id, genre_name) VALUES (311, 'hardcore hip hop');
INSERT INTO Genres (genre_id, genre_name) VALUES (312, 'neofolk');
INSERT INTO Genres (genre_id, genre_name) VALUES (313, 'boogaloo');
INSERT INTO Genres (genre_id, genre_name) VALUES (314, 'beat');
INSERT INTO Genres (genre_id, genre_name) VALUES (315, 'italian disco');
INSERT INTO Genres (genre_id, genre_name) VALUES (316, 'hardstyle');
INSERT INTO Genres (genre_id, genre_name) VALUES (317, 'swamp blues');
INSERT INTO Genres (genre_id, genre_name) VALUES (318, 'marrabenta');
INSERT INTO Genres (genre_id, genre_name) VALUES (319, 'banda');
INSERT INTO Genres (genre_id, genre_name) VALUES (320, 'san francisco bay area');
INSERT INTO Genres (genre_id, genre_name) VALUES (321, 'vallenato');
INSERT INTO Genres (genre_id, genre_name) VALUES (322, 'ragga jungle');
INSERT INTO Genres (genre_id, genre_name) VALUES (323, 'mambo');
INSERT INTO Genres (genre_id, genre_name) VALUES (324, 'emo');
INSERT INTO Genres (genre_id, genre_name) VALUES (325, 'power violence');
INSERT INTO Genres (genre_id, genre_name) VALUES (326, 'dirty rap');
INSERT INTO Genres (genre_id, genre_name) VALUES (327, 'tribal house');
INSERT INTO Genres (genre_id, genre_name) VALUES (328, 'glam');
INSERT INTO Genres (genre_id, genre_name) VALUES (329, 'melodic trance');
INSERT INTO Genres (genre_id, genre_name) VALUES (330, 'east coast blues');
INSERT INTO Genres (genre_id, genre_name) VALUES (331, 'nu jazz');
INSERT INTO Genres (genre_id, genre_name) VALUES (332, 'memphis blues');
INSERT INTO Genres (genre_id, genre_name) VALUES (333, 'skate punk');
INSERT INTO Genres (genre_id, genre_name) VALUES (334, 'soul');
INSERT INTO Genres (genre_id, genre_name) VALUES (335, 'acid jazz');
INSERT INTO Genres (genre_id, genre_name) VALUES (336, 'hardcore metal');
INSERT INTO Genres (genre_id, genre_name) VALUES (337, 'bolero');
INSERT INTO Genres (genre_id, genre_name) VALUES (338, 'bebop');
INSERT INTO Genres (genre_id, genre_name) VALUES (339, 'chanson francaise');
INSERT INTO Genres (genre_id, genre_name) VALUES (340, 'synth punk');
INSERT INTO Genres (genre_id, genre_name) VALUES (341, 'lo-fi');
INSERT INTO Genres (genre_id, genre_name) VALUES (342, 'deathrock');
INSERT INTO Genres (genre_id, genre_name) VALUES (343, 'chamber music');
INSERT INTO Genres (genre_id, genre_name) VALUES (344, 'funeral doom');
INSERT INTO Genres (genre_id, genre_name) VALUES (345, 'noise pop');
INSERT INTO Genres (genre_id, genre_name) VALUES (346, 'electroclash');
INSERT INTO Genres (genre_id, genre_name) VALUES (347, 'psychobilly');
INSERT INTO Genres (genre_id, genre_name) VALUES (348, 'marimba');
INSERT INTO Genres (genre_id, genre_name) VALUES (349, 'big band');
INSERT INTO Genres (genre_id, genre_name) VALUES (350, 'funk rock');
INSERT INTO Genres (genre_id, genre_name) VALUES (351, 'merseybeat');
INSERT INTO Genres (genre_id, genre_name) VALUES (352, 'straight edge');
INSERT INTO Genres (genre_id, genre_name) VALUES (353, 'female vocalist');
INSERT INTO Genres (genre_id, genre_name) VALUES (354, 'calypso');
INSERT INTO Genres (genre_id, genre_name) VALUES (355, 'bulerias');
INSERT INTO Genres (genre_id, genre_name) VALUES (356, 'southern soul');
INSERT INTO Genres (genre_id, genre_name) VALUES (357, 'nu-soul');
INSERT INTO Genres (genre_id, genre_name) VALUES (358, 'symphonic metal');
INSERT INTO Genres (genre_id, genre_name) VALUES (359, 'sxsw 2007');
INSERT INTO Genres (genre_id, genre_name) VALUES (360, 'chorus');
INSERT INTO Genres (genre_id, genre_name) VALUES (361, 'japanese');
INSERT INTO Genres (genre_id, genre_name) VALUES (362, 'electropop');
INSERT INTO Genres (genre_id, genre_name) VALUES (363, 'folktronica');
INSERT INTO Genres (genre_id, genre_name) VALUES (364, 'illbient');
INSERT INTO Genres (genre_id, genre_name) VALUES (365, 'swamp pop');
INSERT INTO Genres (genre_id, genre_name) VALUES (366, 'chant');
INSERT INTO Genres (genre_id, genre_name) VALUES (367, 'post rock');
INSERT INTO Genres (genre_id, genre_name) VALUES (368, 'alternative');
INSERT INTO Genres (genre_id, genre_name) VALUES (369, 'christian music');
INSERT INTO Genres (genre_id, genre_name) VALUES (370, 'math rock');
INSERT INTO Genres (genre_id, genre_name) VALUES (371, 'jam band');
INSERT INTO Genres (genre_id, genre_name) VALUES (372, 'indie');
INSERT INTO Genres (genre_id, genre_name) VALUES (373, 'latin');
INSERT INTO Genres (genre_id, genre_name) VALUES (374, 'outlaw country');
INSERT INTO Genres (genre_id, genre_name) VALUES (375, 'comedy rap');
INSERT INTO Genres (genre_id, genre_name) VALUES (376, 'celtic fusion');
INSERT INTO Genres (genre_id, genre_name) VALUES (377, 'dj');
INSERT INTO Genres (genre_id, genre_name) VALUES (378, 'christian hardcore');
INSERT INTO Genres (genre_id, genre_name) VALUES (379, 'no wave');
INSERT INTO Genres (genre_id, genre_name) VALUES (380, 'merengue');
INSERT INTO Genres (genre_id, genre_name) VALUES (381, 'contemporary classical music');
INSERT INTO Genres (genre_id, genre_name) VALUES (382, 'batucada');
INSERT INTO Genres (genre_id, genre_name) VALUES (383, 'mexico');
INSERT INTO Genres (genre_id, genre_name) VALUES (384, 'canadian');
INSERT INTO Genres (genre_id, genre_name) VALUES (385, 'hyphy');
INSERT INTO Genres (genre_id, genre_name) VALUES (386, 'ost');
INSERT INTO Genres (genre_id, genre_name) VALUES (387, 'detroit techno');
INSERT INTO Genres (genre_id, genre_name) VALUES (388, 'mondiovision');
INSERT INTO Genres (genre_id, genre_name) VALUES (389, 'classical');
INSERT INTO Genres (genre_id, genre_name) VALUES (390, 'new orleans jazz');
INSERT INTO Genres (genre_id, genre_name) VALUES (391, 'electro rock');
INSERT INTO Genres (genre_id, genre_name) VALUES (392, 'funny');
INSERT INTO Genres (genre_id, genre_name) VALUES (393, 'old school hip hop');
INSERT INTO Genres (genre_id, genre_name) VALUES (394, 'mandarin pop');
INSERT INTO Genres (genre_id, genre_name) VALUES (395, 'rebetika');
INSERT INTO Genres (genre_id, genre_name) VALUES (396, 'indie pop');
INSERT INTO Genres (genre_id, genre_name) VALUES (397, 'united states');
INSERT INTO Genres (genre_id, genre_name) VALUES (398, 'klezmer');
INSERT INTO Genres (genre_id, genre_name) VALUES (399, 'queercore');
INSERT INTO Genres (genre_id, genre_name) VALUES (400, 'riot grrrl');
INSERT INTO Genres (genre_id, genre_name) VALUES (401, 'alternative pop rock');
INSERT INTO Genres (genre_id, genre_name) VALUES (402, 'swedish');
INSERT INTO Genres (genre_id, genre_name) VALUES (403, 'melodic death metal');
INSERT INTO Genres (genre_id, genre_name) VALUES (404, 'sonata');
INSERT INTO Genres (genre_id, genre_name) VALUES (405, 'show tunes');
INSERT INTO Genres (genre_id, genre_name) VALUES (406, 'progressive metal');
INSERT INTO Genres (genre_id, genre_name) VALUES (407, 'slow core');
INSERT INTO Genres (genre_id, genre_name) VALUES (408, 'americana');
INSERT INTO Genres (genre_id, genre_name) VALUES (409, 'neoclassical');
INSERT INTO Genres (genre_id, genre_name) VALUES (410, 'dubtronica');
INSERT INTO Genres (genre_id, genre_name) VALUES (411, 'musica');
INSERT INTO Genres (genre_id, genre_name) VALUES (412, 'country music');
INSERT INTO Genres (genre_id, genre_name) VALUES (413, 'game');
INSERT INTO Genres (genre_id, genre_name) VALUES (414, 'kirtan');
INSERT INTO Genres (genre_id, genre_name) VALUES (415, 'peace punk');
INSERT INTO Genres (genre_id, genre_name) VALUES (416, 'guitarist');
INSERT INTO Genres (genre_id, genre_name) VALUES (417, 'swiss');
INSERT INTO Genres (genre_id, genre_name) VALUES (418, 'kizomba');
INSERT INTO Genres (genre_id, genre_name) VALUES (419, 'british blues');
INSERT INTO Genres (genre_id, genre_name) VALUES (420, 'choro');
INSERT INTO Genres (genre_id, genre_name) VALUES (421, 'highlife');
INSERT INTO Genres (genre_id, genre_name) VALUES (422, 'massachusetts');
INSERT INTO Genres (genre_id, genre_name) VALUES (423, 'alternative rap');
INSERT INTO Genres (genre_id, genre_name) VALUES (424, 'world fusion');
INSERT INTO Genres (genre_id, genre_name) VALUES (425, 'disco house');
INSERT INTO Genres (genre_id, genre_name) VALUES (426, 'soul music');
INSERT INTO Genres (genre_id, genre_name) VALUES (427, 'goa');
INSERT INTO Genres (genre_id, genre_name) VALUES (428, 'trip rock');
INSERT INTO Genres (genre_id, genre_name) VALUES (429, 'spanish');
INSERT INTO Genres (genre_id, genre_name) VALUES (430, 'finish');
INSERT INTO Genres (genre_id, genre_name) VALUES (431, 'folk punk');
INSERT INTO Genres (genre_id, genre_name) VALUES (432, 'space music');
INSERT INTO Genres (genre_id, genre_name) VALUES (433, 'german');
INSERT INTO Genres (genre_id, genre_name) VALUES (434, 'Russian Easter Festival_ Overture_ Op.36');
INSERT INTO Genres (genre_id, genre_name) VALUES (435, 'psychedelic rock');
INSERT INTO Genres (genre_id, genre_name) VALUES (436, 'space rock');
INSERT INTO Genres (genre_id, genre_name) VALUES (437, 'desi');
INSERT INTO Genres (genre_id, genre_name) VALUES (438, 'electro hip hop');
INSERT INTO Genres (genre_id, genre_name) VALUES (439, 'melodic metalcore');
INSERT INTO Genres (genre_id, genre_name) VALUES (440, 'concerto');
INSERT INTO Genres (genre_id, genre_name) VALUES (441, 'speed garage');
INSERT INTO Genres (genre_id, genre_name) VALUES (442, 'pinoy rock');
INSERT INTO Genres (genre_id, genre_name) VALUES (443, 'punk blues');
INSERT INTO Genres (genre_id, genre_name) VALUES (444, 'christian punk');
INSERT INTO Genres (genre_id, genre_name) VALUES (445, 'fusion');
INSERT INTO Genres (genre_id, genre_name) VALUES (446, 'dance music');
INSERT INTO Genres (genre_id, genre_name) VALUES (447, 'close harmony');
INSERT INTO Genres (genre_id, genre_name) VALUES (448, 'ambient black metal');
INSERT INTO Genres (genre_id, genre_name) VALUES (449, 'boy band');
INSERT INTO Genres (genre_id, genre_name) VALUES (450, 'progressive bluegrass');
INSERT INTO Genres (genre_id, genre_name) VALUES (451, 'lounge music');
INSERT INTO Genres (genre_id, genre_name) VALUES (452, 'vocal trance');
INSERT INTO Genres (genre_id, genre_name) VALUES (453, 'rare groove');
INSERT INTO Genres (genre_id, genre_name) VALUES (454, 'chalga');
INSERT INTO Genres (genre_id, genre_name) VALUES (455, 'sadcore');
INSERT INTO Genres (genre_id, genre_name) VALUES (456, 'east coast hip hop');
INSERT INTO Genres (genre_id, genre_name) VALUES (457, 'manouche');
INSERT INTO Genres (genre_id, genre_name) VALUES (458, 'bubblegum dance');
